version: '3.8'

services:
  app:
    build:
      args:
        work-dir: /var/www/
      context: ./
      dockerfile: Docker/dev.Dockerfile
      target: php
    container_name: inventory-app-dev
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - inventory-dev
  nginx:
    image: nginx:1.19-alpine
    container_name: inventory-nginx-dev
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./Docker/nginx-files:/etc/nginx/conf.d
    networks:
      - inventory-dev
  mysql:
    image: mysql:8.0
    container_name: inventory-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
    networks:
      - inventory-dev
volumes:
  mysql-data-dev:
    driver: local
networks:
  inventory-dev:

