version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Docker/Dockerfile
      target: php
    container_name: inventory-app
    restart: always
    working_dir: /var/www/
  nginx:
    build:
      context: ./
      dockerfile: Docker/Dockerfile
      target: nginx
    container_name: inventory-nginx
    restart: always
    ports:
      - "8080:80"
  mysql:
    image: mysql:8.0.31
    container_name: inventory-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local


