version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: inventory-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
  nginx:
    image: nginx:1.19-alpine
    container_name: inventory-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./nginx:/etc/nginx/conf.d
  mysql:
    image: mysql:8.0.31
    container_name: inventory-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:var/lib/msql
volumes:
  mysql-data:
    driver: local


