version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Docker/prod.Dockerfile
      target: php-prod
    container_name: inventory-app
    env_file:
      - .env.pro
    restart: always
    working_dir: /var/www
    volumes:
      - app-data:/var/www
  nginx-prod:
    build:
      context: ./
      dockerfile: Docker/prod.Dockerfile
      target: nginx
    container_name: inventory-nginx
    env_file:
      - .env.pro
    restart: always
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - app-data:/var/www
  mysql:
    image: mysql:8.0
    container_name: inventory-mysql
    env_file:
      - .env.pro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
  app-data:
    driver: local


